### ISSUE TITLE
can't use --mm:refc with nim 2.2.0

### ISSUE THREAD

**Issue by ITwrx** [olliNiinivaara/SQLiteral#10]
`/home/itwrx/.nimble/pkgs2/sqliteral-4.0.1-62b8e0bea58949234f1d6ecdd40164a86c2e1c5b/sqliteral.nim(174, 1) Error: signature for '=destroy' must be proc[T: object](x: var T)`

same as can-lehmann/owlkettle#176

**Comment by olliNiinivaara** [comment]
As you can see at line 174, destroy hook is being used and therefore the code won't work without a mm supporting gcDestructors. Therefore the correct fix will be to state somewhere in documentation that esoteric mm:s are not supported.

However...
You can easily run SQLiteral (at least for testing purposes) with refc by adding a `var` to 174 as follows:
``proc `=destroy`(x: var DestructorTriggerer) =``

Running with mm:refc will then trigger the sqlite error *unable to close due to unfinalized statements* when the db is closed, for obvious reasons.

If you really really need SQLiteral to work with refc without the error message, it would require the library user (you...) to manually finalize the statements before calling close. Doable, but I am reluctant to work on this, especially because I don't want to hang myself into supporting other mm:s than arc and orc.

**Comment by ITwrx** [comment]
> As you can see at line 174, destroy hook is being used and therefore the code won't work without a mm supporting gcDestructors.

ok, thanks. i don't know what any of that is, so i didn't know what was going on. :)

Thanks for all the info. Yeah, it might be nice for people evaluating the library for use to know that only arc and/or orc are supported. I was wondering about that, in-general, with nim libs and these non-default GCs.

**Comment by olliNiinivaara** [comment]
There is now 5.0.0 branch available for testing.

Good news: The preparation of statements happens now fully automatically on first use, and finalization automatically on close.

Bad news: Due to this automated preparation/finalization dance, refc cannot be used. I solved this harshly by making the compilation to halt if mm is not ARC or ORC.

**Comment by ITwrx** [comment]
Sounds good to me! Thanks for the info.
