### ISSUE TITLE
malloc error when using a slightly adapted version of the json example

### ISSUE THREAD

**Issue by jgdevop** [olliNiinivaara/SQLiteral#4]
inserting 10000 rows...
10000 rows inserted. Press <Enter> to select all in 4 threads...

test(69687,0x70000d8d6000) malloc: *** error for object 0x7fbf67015000: pointer being freed was not allocated
test(69687,0x70000d8d6000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: Abnormal termination.
zsh: abort      ./test

[Example (using JSON extensions)](https://olliniinivaara.github.io/SQLiteral/#example-using-json-extensions)
with the output disabled
 28     for row in db.rows(Select):
 29       #stdout.write(row.getCString(0))
 30       #stdout.write('\n')
 31       continue
 32     discard ready.atomicInc

(I noticed the same effect when redirecting the stdout to a file )

**Comment by olliNiinivaara** [comment]
I cannot reproduce but then I am using Linux and you seem to be using MacOS. I can accept that not using the row at all can lead to issues (due to compiler optimizations), but the same effect also when redirecting to file appears as a bug. Please try with different compiler switches and also try compiling to c++ and check whether the problem persists. Switches that hopefully could rescue the situation are:
--mm:orc
-d:useMalloc
--opt:none

**Comment by olliNiinivaara** [comment]
Now that Nim 2 and SQLiteral 4 are out, let us assume that the problem might not exist anymore. Reopen if this was wishful thinking.
